language: python
python:
  - "3.6"
cache: pip
install:
  - pip install coverage pushbullet.py
script:
  - coverage run -m unittest discover
  - coverage report --include="stuns/*"
notifications:
  email: false
