version: '3'
services:
    demdata_mongodb:
        container_name: demdata_mongodb
        image: mongo
        expose:
            - 27017
        ports:
            - "9090:27017"
        networks:
            - demdata_network
        volumes:
            - /var/tmp/mongodb-databases:/data/db
    demdata_api:
        image: demdata/api-services
        environment:
            spring.data.mongodb.host: demdata_mongodb
            morphia.db_name: demdata_db
            JVM_OPTS: -Xmx1g -Xms512m -XX:MaxPermSize=512m
        networks:
            - demdata_network
        volumes:
          - /var/tmp/demdata_images:/var/tmp/demdata_images
        expose:
            - 8080
        links:
            - demdata_mongodb:demdata_mongodb
        depends_on:
            - demdata_mongodb
    demdata_ui:
        image: demdata/ui
        networks:
            - demdata_network
        expose:
            - 80
        links:
            - demdata_api:demdata_api
        depends_on:
          - demdata_api
    nginx_proxy:
        image: nginx:alpine
        networks:
            - demdata_network
        ports:
            - "80:80"
        links:
            - demdata_api:demdata_api
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
          - demdata_api
    extra_api:
        image: extra_api
        networks:
            - demdata_network
        build:
            context: ./api
        container_name: extra_api
        ports:
            - '5050:5050'
        depends_on:
            - demdata_mongodb
networks:
    demdata_network:
        driver: bridge
